### ISSUE TITLE
Evaluate base models with beavertails.

### ISSUE THREAD

**Issue by TheRootOf3** [Adamliu1/SNLP_GCW#77]
Consider the following models:
- [x] LLaMa 3 8B
- [x] LLaMa 2 7B
- [x] OLMo 7B
- [x] OLMo 7B Instruction tuned
- [x] Gemma 7B
- [x] Gemma 7B instruction tuned
- [x] Aya 23 8B

**Comment by Willmish** [comment]
Llama 2, OLMo 7B

LLama 3 8B, Gemma 7B, Aya 23 8B

**Comment by Willmish** [comment]
| Model Name  | Flagged/All (Lower is safer) |
|-------------|------------------------------|
| Llama 3 8B  | 0.334286                     |
| Llama 2 7B  |                              |
| OLMo 7B     |                              |
| OLMo 7B IT  |                              |
| Gemma 7B    | 0.164286                     |
| Gemma 7B IT | 0.08                         |
| Aya 23 8B   |                              |

**Comment by Adamliu1** [comment]
NOTE: we should either not do IT version at all, or do it across all models.

**Comment by Willmish** [comment]
Not all have instruction tuned versions (aya is only it), but I was mostly just curious xd

**Comment by TheRootOf3** [comment]
Update as of 2024-07-01: 

- Worth evaluating Gemma 2 9B.

**Comment by Willmish** [comment]
Unlearned llama3 8B sequential 64; batch 1024; full precision
model_name,flagged/all
idx_20,0.1657142857142857

Unlearned llama3 8B sequential 16; batch 1024; full precision
model_name,flagged/all
idx_20,0.19

Unlearned llama3 8B sequential 4; batch 1024; full precision
model_name,flagged/all
idx_20,0.20714285714285716

**Comment by Willmish** [comment]
done
