### ISSUE TITLE
STANDARDISE: Make llm unlearning without or with the scheduler a default

### ISSUE THREAD

**Issue by TheRootOf3** [Adamliu1/SNLP_GCW#78]

**Comment by Willmish** [comment]
With scheduler:
![image](https://github.com/user-attachments/assets/7058bebc-50fd-44ff-b4e9-130957e00fca)

Without scheduler:
![image](https://github.com/user-attachments/assets/61bc9ceb-9618-4ae1-9db7-b8febae4fdfa)

Comparison of the two:

![image](https://github.com/user-attachments/assets/b30cd6a1-8513-4e7c-b12c-f5b4a8abc13d)



Verdict : not a lot of change when small LRs used, lets use with scheduler

**Comment by TheRootOf3** [comment]
@Willmish made extra giga chad experiments, so we USE A SCHEDULER. 
![9167yd](https://github.com/user-attachments/assets/881f6f88-87e8-4410-9297-85451a67531f)
