### ISSUE TITLE
Collect a list of all datasets used

### ISSUE THREAD

**Issue by Willmish** [Adamliu1/SNLP_GCW#90]
Updated 2024-07-07.

Datasets:
- Used for evaluation:
  - MMLU: https://huggingface.co/datasets/hails/mmlu_no_train
  - ARC-Challenge: https://huggingface.co/datasets/allenai/ai2_arc 
  - HellaSwag: https://huggingface.co/datasets/Rowan/hellaswag
  - GSM8K (? look below): https://huggingface.co/datasets/openai/gsm8k
  - Winogrande: https://huggingface.co/datasets/allenai/winogrande 
  - TruthfulQA MC2: https://huggingface.co/datasets/truthfulqa/truthful_qa
  - PIQA: https://huggingface.co/datasets/ybisk/piqa
  - French:
    - FrenchBench:
  - Harmfulness:
    - [PKU-Alignment/BeaverTails](https://huggingface.co/datasets/PKU-Alignment/BeaverTails)
    - [toxigen](https://huggingface.co/datasets/toxigen/toxigen-data)
    - (? probably not) [realtoxicityprompts](https://huggingface.co/datasets/allenai/real-toxicity-prompts)
  - Logical reasoning:
    - ~[lucasmccabe/logiqa](https://huggingface.co/datasets/lucasmccabe/logiqa)~
    - [mnli](https://huggingface.co/datasets/nyu-mll/multi_nli) instead of LogiQA.
  - ...
- Used for unlearning:
  - Unlearn Sets:
    - French: [AgentPublic/piaf](https://huggingface.co/datasets/AgentPublic/piaf)
    - Harmfulness: [PKU-Alignment/PKU-SafeRLHF](https://huggingface.co/datasets/PKU-Alignment/PKU-SafeRLHF)
    - Logical reasoning: [sail/symbolic-instruction-tuning](https://huggingface.co/datasets/sail/symbolic-instruction-tuning)
  - Retain Sets:
    - [squad](https://huggingface.co/datasets/rajpurkar/squad) (with eval on [squadv2](https://huggingface.co/datasets/rajpurkar/squad_v2) because of availability in lm-eval-harness)
    - ~~[google-research-datasets/nq_open](https://huggingface.co/datasets/google-research-datasets/nq_open) or [truthfulqa/truthful_qa](https://huggingface.co/datasets/truthfulqa/truthful_qa) (repeat-padded)?~~

**Comment by TheRootOf3** [comment]
Sent to Eduardo on 04-06-2024!

**Comment by TheRootOf3** [comment]
Update on 2024-07-01: 
@TheRootOf3 Reconsider adding toxigen as well as real toxicity prompts. 
- https://huggingface.co/datasets/toxigen/toxigen-data
- https://huggingface.co/datasets/allenai/real-toxicity-prompts

**Comment by Willmish** [comment]
Move to markdown doc Pls!!!!!!!!! @TheRootOf3
