### ISSUE TITLE
beavertails multiple run, majority voting for result consistency

### ISSUE THREAD

**Issue by Adamliu1** [Adamliu1/SNLP_GCW#91]
Run Beavertails evaluation more than once for consistent results. Retry with diff seeds! (Check if beavertails eval reproducible on diff seeds) (5) Rather than average, do majority voting over 5 seeds for each question (⅗ unsafe -> unsafe response to that q)

**Comment by TheRootOf3** [comment]
What's the progress on this one? @Adamliu1 @Willmish
